=== ashvik/steps/step-core/src/main/resources/step.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.stepframework.com/StepRequestMapper"
           xmlns="http://www.stepframework.com/StepRequestMapper">
    <xs:element name="stepRequestMapper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="multiScopedSteps" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="step" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="scope" maxOccurs="unbounded" minOccurs="1">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="request" use="required"/>
                                                        <xs:attribute type="xs:string" name="nextStep" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mappedRequest" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="contract" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="requiredInputs" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="inputType" maxOccurs="unbounded" minOccurs="1"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="expectedOutcome" minOccurs="0" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="exceptionHandler" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="jumper" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="forStep" use="required"/>
                                            <xs:attribute type="xs:string" name="conditionClass" use="required"/>
                                            <xs:attribute type="xs:string" name="onSuccessJumpTo" use="required"/>
                                            <xs:attribute type="xs:string" name="onFailureJumpTo" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="breaker" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="forStep" use="required"/>
                                            <xs:attribute type="xs:string" name="conditionClass" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="repeater" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="forStep" use="required"/>
                                            <xs:attribute type="xs:string" name="conditionClass" use="required"/>
                                            <xs:attribute type="xs:string" name="repeatFromStep" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pluginRequest" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="name" use="required"/>
                                            <xs:attribute type="xs:string" name="runAutomatically" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="preSteps" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="step" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="postSteps" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="step" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="requestParameters" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="configuration" minOccurs="0" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="xs:string" name="ref" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="parameter" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="value" maxOccurs="unbounded" minOccurs="1"/>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="name" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="request" use="required"/>
                        <xs:attribute type="xs:string" name="rootStep" use="required"/>
                        <xs:attribute type="xs:string" name="applyGenericSteps" use="optional"/>
                        <xs:attribute type="xs:string" name="onSuccess" use="optional"/>
                        <xs:attribute type="xs:string" name="onFailure" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="parameterConfiguration" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="parameter" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="value" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ashvik/steps/step-core/src/main/resources/step-conf-EXAMPLE.xml
<?xml version="1.0" encoding="UTF-8"?>
<stepRequestMapper xsi:schemaLocation="step.xsd">
    <multiScopedSteps>
        <step name="#">
            <scope request="#" nextStep="#"/>
            <scope request="#" nextStep="#"/>
        </step>
    </multiScopedSteps>
    <mappedRequest request="#" rootStep="#" applyGenericSteps="#" onSuccess="#" onFailure="#">
        <jumper forStep="#" conditionClass="#" onSuccessJumpTo="#" onFailureJumpTo="#"/>
        <breaker forStep="#" conditionClass="#"/>
        <repeater forStep="#" conditionClass="#" repeatFromStep="#"/>
        <pluginRequest name="#"/>
        <preSteps>
            <step>1</step>
            <step>2</step>
        </preSteps>
        <postSteps>
            <step>3</step>
        </postSteps>
    </mappedRequest>
    
    <mappedRequest request="#" rootStep="#" onSuccess="#" onFailure="#">
        <preSteps>
            <step>4</step>
            <step>5</step>
        </preSteps>
        <postSteps>
            <step>6</step>
            <step>7</step>
        </postSteps>
    </mappedRequest>
</stepRequestMapper>
